services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - ./jenkins-data:/var/jenkins_home
    ports:
      - "2375:2375"
    command: [ "--storage-driver", "overlay2", "--insecure-registry", "registry-server:5000" ]

  jenkins-blueocean:
    build:
      context: .
      dockerfile: Dockerfile
    image: myjenkins-blueocean:2.541.3-1
    container_name: jenkins-blueocean
    restart: on-failure
    depends_on:
      - jenkins-docker
    networks:
      - jenkins
    environment:
      DOCKER_HOST: tcp://docker:2375
      TZ: Asia/Shanghai
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins-data:/var/jenkins_home

  registry-ui:
    image: joxit/docker-registry-ui:2.5.7
    restart: always
    depends_on:
      registry-server:
        condition: service_healthy
    networks:
      - jenkins
    ports:
      - 8090:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry-server:5000
      - SHOW_CATALOG_NB_TAGS=true
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-ui

  registry-server:
    image: registry:2.8.2
    restart: always
    networks:
      - jenkins
    environment:
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: '[http://registry.example.com]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '[HEAD,GET,OPTIONS,DELETE]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: '[true]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '[Authorization,Accept,Cache-Control]'
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '[Docker-Content-Digest]'
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    volumes:
      - ./registry/data:/var/lib/registry
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:5000/v2/ >/dev/null 2>&1 || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 10
    container_name: registry-server

networks:
  jenkins:
    external: true
    name: jenkins
